window.struct_09 = {
	ver: 9,
	editorVer: "09",
	main: [
		"unknown_head", "int16",
		"sht_off_cnt", "int16",
		"unknown_pofv_0", "float", 
		"hitbox_u", "float", // leftover values
		"grazebox_u", "float",
		"itembox_u", "float",
		"move_nf_str", "float",
		"move_f_str", "float",
		"move_nf_dia", "float",
		"move_f_dia", "float",
		"unknown_pofv_1", "float",
		"unknown_pofv_2", "float",
		"spellname_arr", "spellname_arr",
		"sht_off", "sht_off",
		"sht_arr", "sht_arr"
	],
	sht_off: [
		"offset", "uint32",
		"power", "uint32"
	],
	sht_arr: [
		"fire_rate", "int16",
		"start_delay", "int16",
		"off_x", "float",
		"off_y", "float",
		"hitbox_x", "float",
		"hitbox_y", "float",
		"angle", "float",
		"speed", "float",
		"dmg", "int16",
		"unknown_old_sht_0", "int16",
		"option", "byte",
		"unknown_old_sht_1", "byte",
		"unknown_old_sht_2", "int16",
		"anm", "int16",
		"sfx_id", "int16",
		"flags", "flags",
		"func_on_init", "int32",
		"func_on_tick", "int32",
		"func_on_draw", "int32",
		"func_on_hit", "int32"
	],
	sht_off_type: "abs",
	option_pos_len: false, 
	max_opt: false, 
	flags_len: 0x0,
	flag_size: 2,
	type: "maingame",
	forced_shtoffarr_len: false,
	f_uf_shooter_split: false,
	spellname_arr_len: 0x10,
	spellname_len: 0x40
};
