window.struct_14 = {
	ver: 14,
	editorVer: "14",
	main: [
		"unknown_head", "int16",
		"sht_off_cnt", "int16",
		"hitbox_u", "float",
		"grazebox_u", "float",
		"itembox_u", "float",
		"move_nf_str", "float",
		"move_f_str", "float",
		"move_nf_dia", "float",
		"move_f_dia", "float",
		"pwr_lvl_cnt", "int16",
		"max_dmg_u", "int16",
		"SA_power_divisor", "int32",
		"max_dmg", "int32",
		"unknown_2", "int32",
		"unknown_3", "int32",
		"unknown_4", "int32",
		"unknown_5", "int32",
		"unknown_6", "int32",
		"option_pos", "option_pos",
		"sht_off", "sht_off",
		"sht_arr", "sht_arr"
	],
	option_pos: [
		"x", "float",
		"y", "float"
	],
	sht_off: [
		"offset", "uint32"
	],
	sht_arr: [
		"fire_rate", "byte",
		"start_delay", "byte",
		"dmg", "int16",
		"off_x", "float",
		"off_y", "float",
		"hitbox_x", "float",
		"hitbox_y", "float",
		"angle", "float",
		"speed", "float",
		"unknown_sht_int32", "int32",
		"option", "byte",
		"unknown_sht_byte_0", "byte",
		"anm", "byte",
		"anm_hit", "byte",
		"sfx_id", "int16",
		"unknown_sht_int16", "int16", // NOT rate2/delay2
		"func_on_init", "int32",
		"func_on_tick", "int32",
		"_old_on_draw", "int32",
		"func_on_hit", "int32",
		"flags", "flags"
	],
	sht_off_type: "rel",
	option_pos_len: 0xA0,
	max_opt: 0x04,
	flags_len: 0x20,
	flag_size: 2,
	type: "maingame",
	forced_shtoffarr_len: 0x0A,
	f_uf_shooter_split: true
};
